### ISSUE TITLE
How to add openCV?

### ISSUE THREAD

**Issue by EbelloImbox** [hannesa2/CVScanner#155]
Hello, I am trying to use this library, I add the last version 1,7 to my gradle and everything works fine, but when I try to compile my project the following error is shown:

Could not find OpenCV_all_together_samples:opencv:4.5.4.0.
Required by:
    project : myProject > com.github.hannesa2:CVScanner:1.7

How can I add openCV? I can't see it in your example app.

Thank you

**Comment by hannesa2** [comment]
Here it is
https://github.com/hannesa2/CVScanner/blob/master/build.gradle#L27-L28

**Comment by EbelloImbox** [comment]
I am trying to add openCV, but this is my error:

More than one file was found with OS independent path 'lib/x86/libc++_shared.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

I have tried to add the project by my own following some tutorials, but I have always the same problem, can you help me?

**Comment by hannesa2** [comment]
you need `lib/x86/libc++_shared.so`

**Comment by EbelloImbox** [comment]
Hello @hannesa2 I really tried to use this solution and other like this with different paths but without results, I always have a similar error, any tip?

**Comment by hannesa2** [comment]
Please share you project

**Comment by EbelloImbox** [comment]
Finally I get that openCV works in my project. 

I have a common project with more than one gradle and the problem was that I was using it in the common gradle and I have to put the exceptions in all specific gradles. Forthermore I have to use another exclude in my projects:

exclude 'META-INF/library_release.kotlin_module'
pickFirst 'lib/x86/libc++_shared.so'
pickFirst 'lib/arm64-v8a/libc++_shared.so'
pickFirst 'lib/x86_64/libc++_shared.so'
pickFirst 'lib/armeabi-v7a/libc++_shared.so'

**Comment by hannesa2** [comment]
I guess you have multiple `implementation 'com.github.hannesa2:CVScanner:$latest'`

maybe a single `api 'com.github.hannesa2:CVScanner:$latest'` will help
