### ISSUE TITLE
Receive a list of uris

### ISSUE THREAD

**Issue by EbelloImbox** [hannesa2/CVScanner#162]
Hello, is there any possibility to create a method for startManualCropper to receive a list of uris and crop it one by one?

**Comment by hannesa2** [comment]
Of course

    fun startManualCropper(activity: Activity, inputImageUri: Uri, reqCode: Int) {
        val intent = Intent(activity, CropImageActivity::class.java)
        intent.putExtra(CropImageActivity.EXTRA_IMAGE_URI, inputImageUri.toString())
        activity.startActivityForResult(intent, reqCode)
    }

You have to catch `reqCode` and bring your `uris` back there.

similar to this 

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (resultCode == RESULT_OK) {
            if (requestCode == YOUR_CODE) {
                val uris = data?.getParcelableArrayListExtra("uris") // eg. as Parcel
                val uris = data?.getStringExtra("uris").toYourList() // eg. or serialized List
```

**Comment by EbelloImbox** [comment]
I didn't explain it very well. I would like to pass a list of uris to startManualCropper to crop for an example a couple of images, but I only can pass one Uri to startManualCropper.

```
private fun addCropperFragment() {
        var imageUri: Uri? = null
        val extras = intent.extras
        if (extras != null) {
            imageUri = Uri.parse(extras.getString(EXTRA_IMAGE_URI))
        }
```

**Comment by hannesa2** [comment]
I'm confused `startManualCropper` != `addCropperFragment` 
Isn't is easier when you make a pull request and I approve it ?
