### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by EbelloImbox** [hannesa2/CVScanner#165]
Hello, can you make new version 1.8? I am having some issues with dependencies when you make a new commit because I am using:

`implementation 'com.github.hannesa2:CVScanner:FixNPE-SNAPSHOT'`

for this issue https://github.com/hannesa2/CVScanner/issues/159

**Comment by hannesa2** [comment]
Here you go https://github.com/hannesa2/CVScanner/releases/tag/1.8
