### ISSUE TITLE
Image is rotated 90º to the left 

### ISSUE THREAD

**Issue by AlejandroImbox** [hannesa2/CVScanner#170]
Hello,

I am integrating the library and I am facing the following problem:

When I take a picture with the mobile camera and call **startManualCropper** I get back the image rotated 90º to the left. Also in some occasions it happens to me with photos loaded from the gallery.

I have noticed that when I ask for the orientation of the image it returns **ORIENTATION_UNDEFINED**
 I have tried to rotate it manually but I can't get it.

I attach two images to show the behavior, the first one is before scanning and the second one is the result.

Would you know how to fix it?

Thank you very much. 

![before_scan](https://user-images.githubusercontent.com/93912284/143905625-97508c52-5dcd-4d45-ae74-75ef6358e567.jpg)
![after_scan](https://user-images.githubusercontent.com/93912284/143905637-34654156-abef-471b-a902-7fe15e5a27af.jpg)

**Comment by hannesa2** [comment]
At the first look, sorry I don't know. 
I would have to debug too, but the cool thing it's open source. That's why, I'm not the only one, who can do this.

**Comment by AlejandroImbox** [comment]
I will continue with it, thank you very much.
