### ISSUE TITLE
The rotation buttons do not work

### ISSUE THREAD

**Issue by AlejandroImbox** [hannesa2/CVScanner#172]
Hello, when you rotate the image with the scanner's own rotate option, it does not work.

Is there any way to disable these buttons?

thank you very much.

**Comment by hannesa2** [comment]
Can you send me a picture ?

**Comment by AlejandroImbox** [comment]
Of course, I am referring to the buttons with the red circle

![before_scan](https://user-images.githubusercontent.com/93912284/144568190-e1878606-474f-48ba-b6b1-4741840d1eee.jpg)

**Comment by AlejandroImbox** [comment]
Hello,

I have sent you a pull request solving the problem, # 178

thank you very much
